version: 2.1

jobs:
  build:
    working_directory: ~/tmp
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
            at: .
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: cd ./app && npm install && npm run build >  /tmp/python-artifact
      - store_artifacts:
          path: /tmp/python-artifact
          destination: artifact-file
      - persist_to_workspace:
          root: .
          paths:
            - .
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: cd ./app && npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .
 

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
    